#Headers
/gate/geometry/setMaterialDatabase GateMaterials.db 

#Geometries
/gate/world/geometry/setXLength 1 m
/gate/world/geometry/setYLength 1 m
/gate/world/geometry/setZLength 1 m
/gate/world/setMaterial Air

#Scintillator
/gate/world/daughters/name scin
/gate/world/daughters/insert cylinder
/gate/scin/geometry/setRmin 0 m
/gate/scin/geometry/setRmax 3.175 cm
/gate/scin/geometry/setHeight .635 cm
/gate/scin/geometry/setPhiStart 0 rad
/gate/scin/geometry/setDeltaPhi 6.28 rad
/gate/scin/placement/setTranslation 15. 0. 0. cm
/gate/scin/placement/setRotationAngle 90 deg
/gate/scin/placement/setRotationAxis 0 1 0

/gate/scin/setMaterial LYSO

#Physics
/gate/physics/addPhysicsList emstandard #Use higher _opt(number) suffix for more precision

#eDep
/gate/actor/addActor DoseActor edepReadout
/gate/actor/edepReadout/save output/fakestron-90.txt
/gate/actor/edepReadout/stepHitType random
/gate/actor/edepReadout/attachTo scin
/gate/actor/edepReadout/setSize 200 200 200 cm
/gate/actor/edepReadout/setResolution 1 1 1
/gate/actor/edepReadout/enableDose false
/gate/actor/edepReadout/enableEdep true

#Initialization
/gate/geometry/rebuild
/gate/run/initialize

#Actors
/gate/source/addSource stream
/gate/source/stream/gps/particle e-
/gate/source/stream/gps/energytype Mono
/gate/source/stream/gps/monoenergy 2.2 MeV
/gate/source/stream/gps/direction 1 0 0

/gate/output/allowNoOutput

/control/execute visu.mac

/gate/application/setTotalNumberOfPrimaries 2000000
/gate/application/start
