#Things to measure: scintillator height/radius/material, radioactive Source material, type of radiation (in radSource)

##################
#    Preamble    #
#                #
##################
/control/execute visu.mac
/control/execute verbose.mac

###################
#   Configuring   #
#                 #
###################

# Create world
/gate/geometry/setMaterialDatabase GateMaterials.db 
/gate/world/geometry/setXLength 0.2 m
/gate/world/geometry/setYLength 0.2 m
/gate/world/geometry/setZLength 0.2 m
/gate/world/setMaterial Air

# Create Scintillating Slab
/gate/world/daughters/name scintillator
/gate/world/daughters/insert cylinder
/gate/scintillator/setMaterial LYSO #Scintillating material
/gate/scintillator/geometry/setRmin 0 mm
/gate/scintillator/geometry/setRmax 20 mm # Measure this every time please!
/gate/scintillator/geometry/setHeight 4 mm # Measure this every time please!
/gate/scintillator/geometry/setPhiStart 0 deg
/gate/scintillator/geometry/setDeltaPhi 360 deg
/gate/scintillator/vis/setColor yellow

# Create strontium (or other) source
/gate/world/daughters/name radioactiveSource
/gate/world/daughters/insert cylinder
/gate/radioactiveSource/setMaterial Air #Can't have strontium cus it blows up :(
/gate/radioactiveSource/geometry/setRmin 0 mm
/gate/radioactiveSource/geometry/setRmax 1 mm
/gate/radioactiveSource/geometry/setHeight 1 mm
/gate/radioactiveSource/geometry/setPhiStart 0 deg
/gate/radioactiveSource/geometry/setDeltaPhi 360 deg
/gate/radioactiveSource/vis/setColor green
/gate/radioactiveSource/placement/setTranslation 0 0 4 cm

###############
# Information #
#             #
###############

/gate/physics/addPhysicsList emstandard #Use higher _opt(number) suffix for more precision

##################
#  Moving Parts  #
#                #
##################


# Actors

# Energy Deposition readout
/gate/actor/addActor DoseActor edepReadout
/gate/actor/edepReadout/save slabROut.txt #Comment this one out if you don't want to record
/gate/actor/edepReadout/stepHitType random
/gate/actor/edepReadout/attachTo scintillator
/gate/actor/edepReadout/setSize 1000 1000 4 mm
/gate/actor/edepReadout/setResolution 1 1 10
/gate/actor/edepReadout/enableDose false
/gate/actor/edepReadout/enableEdep true

/gate/run/initialize



#Radiation source
/gate/source/addSource radSource gps
/gate/source/radSource/gps/particle e- # Measure
/gate/source/radSource/gps/energytype UserSpectrum # Spectrum file taken from a paper for strontium 90
/gate/source/radSource/gps/setSpectrumFile ../data/strontiumSpectrum.txt
/gate/source/radSource/gps/angtype iso
/gate/source/radSource/gps/mintheta 90. deg
/gate/source/radSource/gps/maxtheta 90. deg
/gate/source/radSource/gps/minphi 90. deg
/gate/source/radSource/gps/maxphi 90. deg
/gate/source/radSource/gps/direction  0 0 -1
/gate/source/radSource/attachTo radioactiveSource

/gate/application/setTotalNumberOfPrimaries 500
/gate/application/start #Start er up!

# halflife=28.8 years
# Age = 11.6 years
# Initial radioactivity = 0.1 microcuries 
# radioactivity remaining = 0.1*0.5^(11.67/28.8) microcuries = 0.0755 microcuries
# 1 Ci is equal to 37 billion (3.7 x 1010) disintegrations per second
# Each source emits 37.*10^9*0.0755*10^-6=2.7935*10^3 disintegrations per second

# Simulated integrated edep for known source = I (integrated energy)
# Experimental photon counting for known source = G (gamma)
# Our photons per MeV will be X=G/I
# Manufacturer provided phontons per MeV will be M
# conversion factor will be A=X/M 
# Count photons for desired material 
#Actual energy deposition = time * D * 