#Testing the penetration of rubber electrical tape by beta particles

/control/execute visu.mac
/control/execute verbose.mac

/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/world/geometry/setXLength 1 m
/gate/world/geometry/setYLength 1 m
/gate/world/geometry/setZLength 1 m
/gate/world/setMaterial Air

/gate/world/daughters/name isotope
/gate/world/daughters/insert cylinder
/gate/isotope/geometry/setRmin 0 m
/gate/isotope/geometry/setRmax 0.01 m
/gate/isotope/geometry/setHeight 0.02 m
/gate/isotope/geometry/setPhiStart 0 deg
/gate/isotope/geometry/setDeltaPhi 360 deg
/gate/isotope/placement/setTranslation 0 0 0.1 m
/gate/isotope/setMaterial Air

/gate/world/daughters/name gblock
/gate/world/daughters/insert box
/gate/gblock/geometry/setXLength 0.1 m
/gate/gblock/geometry/setYLength 0.1 m
/gate/gblock/geometry/setZLength 0.04 m
/gate/gblock/setMaterial Graphite

/gate/world/daughters/name detector
/gate/world/daughters/insert cylinder
/gate/detector/geometry/setRmin 0 m
/gate/detector/geometry/setRmax 0.1 m
/gate/detector/geometry/setHeight 0.1 m
/gate/detector/geometry/setPhiStart 0 deg
/gate/detector/geometry/setDeltaPhi 360 deg
/gate/detector/placement/setTranslation 0 0 -0.1 m
/gate/detector/setMaterial ptpppo

/gate/physics/addPhysicsList emstandard

/gate/actor/addActor DoseActor graphiteEdep
/gate/actor/graphiteEdep/save graphiteTest.txt #Comment this one out if you don't want to record
/gate/actor/graphiteEdep/stepHitType random
/gate/actor/graphiteEdep/attachTo detector
/gate/actor/graphiteEdep/setSize 3 3 0.1 m
/gate/actor/graphiteEdep/setResolution 1 1 5
/gate/actor/graphiteEdep/enableDose false
/gate/actor/graphiteEdep/enableEdep true

/gate/run/initialize

/gate/source/addSource radiation gps
/gate/source/radiation/gps/particle e- # Measure
/gate/source/radiation/gps/ene/type Mono # Spectrum file taken from a paper for strontium 90
/gate/source/radiation/gps/ene/mono 511. keV
/gate/source/radiation/gps/ang/type iso
/gate/source/radiation/gps/ang/mintheta 0. deg
/gate/source/radiation/gps/ang/maxtheta 360. deg
/gate/source/radiation/gps/ang/minphi 90. deg
/gate/source/radiation/gps/ang/maxphi 90. deg
/gate/source/radiation/gps/direction  0 0 -1

/gate/application/setTotalNumberOfPrimaries 1000
/gate/application/start