#Headers
/gate/geometry/setMaterialDatabase GateMaterials.db 

#Geometries
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 2 m
/gate/world/geometry/setZLength 2 m
/gate/world/setMaterial Air

/gate/world/daughters/name scin
/gate/world/daughters/insert box
/gate/scin/geometry/setXLength 1 cm 
/gate/scin/geometry/setYLength 10 cm 
/gate/scin/geometry/setZLength 10 cm 
/gate/scin/placement/setTranslation 60. 0. 0. cm
/gate/scin/setMaterial ptpppo

/gate/world/daughters/name OpticalSystem
/gate/world/daughters/insert box
/gate/OpticalSystem/geometry/setXLength 3 mm 
/gate/OpticalSystem/geometry/setYLength 100 mm 
/gate/OpticalSystem/geometry/setZLength 1 mm 
/gate/OpticalSystem/placement/setTranslation 60. 0. 5. cm
/gate/OpticalSystem/setMaterial ptpppo

/gate/world/daughters/name patient
/gate/world/daughters/insert box
/gate/patient/geometry/setXLength 50 cm 
/gate/patient/geometry/setYLength 50 cm 
/gate/patient/geometry/setZLength 50 cm 
/gate/patient/placement/setTranslation 100. 0. 0. cm
/gate/patient/setMaterial Water

#Define pixelated detector
/gate/OpticalSystem/daughters/name crystal
/gate/OpticalSystem/daughters/insert box
/gate/crystal/geometry/setXLength 3 mm
/gate/crystal/geometry/setYLength 100 mm
/gate/crystal/geometry/setZLength 1 mm
/gate/crystal/setMaterial ptpppo
/gate/systems/OpticalSystem/crystal/attach crystal

/gate/crystal/daughters/name pixel
/gate/crystal/daughters/insert box
/gate/pixel/geometry/setXLength 1.5 mm
/gate/pixel/geometry/setYLength 100 mm
/gate/pixel/geometry/setZLength 1 mm
/gate/pixel/setMaterial ptpppo
/gate/pixel/repeaters/insert linear
/gate/pixel/linear/setRepeatNumber 1
/gate/pixel/linear/setRepeatVector 1.5 0 0 mm
/gate/pixel/attachCrystalSD
/gate/systems/OpticalSystem/pixel/attach pixel
/gate/pixel/vis/setColor blue

#eDep output
/gate/actor/addActor DoseActor eDepsense
/gate/actor/eDepsense/attachTo patient
/gate/actor/eDepsense/setSize 2000 2000 2000 mm
/gate/actor/eDepsense/enableEdep             true
/gate/actor/eDepsense/enableUncertaintyEdep  false
/gate/actor/eDepsense/enableSquaredEdep      false
/gate/actor/eDepsense/enableDose             false
/gate/actor/eDepsense/enableUncertaintyDose  false
/gate/actor/eDepsense/enableSquaredDose      false
/gate/actor/eDepsense/enableNumberOfHits     false
/gate/actor/eDepsense/save output/eDep/AIsim.txt

#Physics
/gate/physics/addPhysicsList G4EmStandardPhysics #Use higher _opt(number) suffix for more precision

#Initialization
/gate/geometry/rebuild
/gate/run/initialize

#Actors
/gate/source/addSource beam
/gate/source/beam/gps/particle e-
/gate/source/beam/gps/energytype Mono
/gate/source/beam/gps/monoenergy 20 MeV
/gate/source/beam/gps/direction 1 0 0
/gate/source/beam/gps/type Volume
/gate/source/beam/gps/shape Sphere
/gate/source/beam/gps/radius 6 mm #get exact dimensions of pulse
/gate/source/beam/gps/centre 0 0 0 cm
/gate/source/beam/visualize 10000 green 2

/control/execute visu.mac

/gate/application/setTimeSlice .01 s
/gate/application/setTimeStart 0 s
/gate/application/setTimeStop 1 s

#/gate/output/root/enable
#/gate/output/root/setFileName output/AIsimROOT
#/gate/output/root/setRootHitFlag 1

/gate/application/setTotalNumberOfPrimaries 1000
/gate/application/start