#Headers
/gate/geometry/setMaterialDatabase GateMaterials.db 

#Geometries
/gate/world/geometry/setXLength 1 m
/gate/world/geometry/setYLength 1 m
/gate/world/geometry/setZLength 1 m
/gate/world/setMaterial Air

/gate/world/daughters/name scintillator
/gate/world/daughters/insert cylinder
/gate/scintillator/geometry/setRmin 0 cm
/gate/scintillator/geometry/setRmax 3.175 cm
/gate/scintillator/geometry/setHeight 4 mm
/gate/scintillator/geometry/setPhiStart 0 rad
/gate/scintillator/geometry/setDeltaPhi 6.28 rad
/gate/scintillator/placement/setTranslation 0 0. -3.5 mm
/gate/scintillator/setMaterial BC412
/gate/scintillator/vis/setColor red

##################################################################################################################################
#OpticalSystem (detector)

# Define the dimensions, position and material
/gate/world/daughters/name OpticalSystem
/gate/world/daughters/insert cylinder
/gate/OpticalSystem/geometry/setRmin 0 mm
/gate/OpticalSystem/geometry/setRmax .5 mm
/gate/OpticalSystem/geometry/setHeight 1 mm
/gate/OpticalSystem/placement/setTranslation 0 0 -5 mm
/gate/OpticalSystem/placement/setRotationAngle 90 deg
/gate/OpticalSystem/placement/setRotationAxis 0 0 1
/gate/OpticalSystem/setMaterial SiO2
/gate/OpticalSystem/vis/setColor yellow

## Define pixelated detector:
/gate/OpticalSystem/daughters/name crystal
/gate/OpticalSystem/daughters/insert cylinder
/gate/crystal/geometry/setRmin 0 cm
/gate/crystal/geometry/setRmax 5 mm
/gate/crystal/geometry/setHeight 1 mm
/gate/crystal/setMaterial BC412
/gate/crystal/vis/setColor magenta
/gate/systems/OpticalSystem/crystal/attach crystal

/gate/crystal/daughters/name pixel
/gate/crystal/daughters/insert cylinder
/gate/crystal/geometry/setRmin 0 mm
/gate/crystal/geometry/setRmax .5 mm
/gate/pixel/geometry/setHeight .1 mm
/gate/pixel/setMaterial BC412
/gate/pixel/vis/setColor blue
/gate/pixel/repeaters/insert linear
/gate/pixel/linear/setRepeatNumber 10
/gate/pixel/linear/setRepeatVector 0 0 -.1 mm
/gate/pixel/attachCrystalSD
/gate/systems/OpticalSystem/pixel/attach pixel
############################################################################################################################################


/gate/world/daughters/name plastic1
/gate/world/daughters/insert cylinder
/gate/plastic1/geometry/setRmin 0 mm
/gate/plastic1/geometry/setRmax 1.27 cm
/gate/plastic1/geometry/setHeight 1 mm
/gate/plastic1/placement/setTranslation 0 0 -.5 mm
/gate/plastic1/placement/setRotationAngle 90 deg
/gate/plastic1/placement/setRotationAxis 0 0 1
/gate/plastic1/setMaterial Plastic
/gate/plastic1/vis/setColor green

/gate/world/daughters/name plastic2
/gate/world/daughters/insert cylinder
/gate/plastic2/geometry/setRmin 0 mm
/gate/plastic2/geometry/setRmax 1.27 cm
/gate/plastic2/geometry/setHeight 3 mm
/gate/plastic2/placement/setTranslation 0 0 0 mm
/gate/plastic2/placement/setRotationAngle 90 deg
/gate/plastic2/placement/setRotationAxis 0 0 1
/gate/plastic2/setMaterial Plastic
/gate/plastic2/vis/setColor green

/gate/world/daughters/name plastic3
/gate/world/daughters/insert cylinder
/gate/plastic3/geometry/setRmin 0 mm
/gate/plastic3/geometry/setRmax 1.27 cm
/gate/plastic3/geometry/setHeight 1 mm
/gate/plastic3/placement/setTranslation 0 0 .5 mm
/gate/plastic3/placement/setRotationAngle 90 deg
/gate/plastic3/placement/setRotationAxis 0 0 1
/gate/plastic3/setMaterial Plastic
/gate/plastic3/vis/setColor green

/gate/world/daughters/name alufoil1
/gate/world/daughters/insert cylinder
/gate/alufoil1/geometry/setRmin 0 mm
/gate/alufoil1/geometry/setRmax 3.175 cm
/gate/alufoil1/geometry/setHeight .1 cm
/gate/alufoil1/placement/setTranslation 0 0 -5.5 mm
/gate/alufoil1/placement/setRotationAngle 90 deg
/gate/alufoil1/placement/setRotationAxis 0 0 1
/gate/alufoil1/setMaterial Aluminium
/gate/alufoil1/vis/setColor white

/gate/world/daughters/name alufoil2
/gate/world/daughters/insert cylinder
/gate/alufoil2/geometry/setRmin 3.175 cm
/gate/alufoil2/geometry/setRmax 3.275 cm
/gate/alufoil2/geometry/setHeight 8 mm
/gate/alufoil2/placement/setTranslation 0 0 -2 mm
/gate/alufoil2/placement/setRotationAngle 90 deg
/gate/alufoil2/placement/setRotationAxis 0 0 1
/gate/alufoil2/setMaterial Aluminium
/gate/alufoil2/vis/setColor white

/gate/world/daughters/name alufoil3
/gate/world/daughters/insert cylinder
/gate/alufoil3/geometry/setRmin 0 cm
/gate/alufoil3/geometry/setRmax 3.175 cm
/gate/alufoil3/geometry/setHeight .1 cm
/gate/alufoil3/placement/setTranslation 0 0 1 mm
/gate/alufoil3/placement/setRotationAngle 90 deg
/gate/alufoil3/placement/setRotationAxis 0 0 1
/gate/alufoil3/setMaterial Aluminium
/gate/alufoil3/vis/setColor white

/gate/actor/addActor DoseActor edepReadout
/gate/actor/edepReadout/save output/irleDepoutput/closerStrontBC412output.txt
/gate/actor/edepReadout/stepHitType random
/gate/actor/edepReadout/attachTo scintillator
/gate/actor/edepReadout/setSize 200 200 200 mm
/gate/actor/edepReadout/setResolution 1 1 1
/gate/actor/edepReadout/enableDose false
/gate/actor/edepReadout/enableEdep true

#Physics
/gate/physics/addPhysicsList emstandard #Use higher _opt(number) suffix for more precision

#Initialization
/gate/geometry/rebuild
/gate/run/initialize

#Actors
/gate/source/addSource str90hist gps
/gate/source/str90hist/gps/particle e-
/gate/source/str90hist/gps/energytype UserSpectrum
/gate/source/str90hist/gps/setSpectrumFile /home/uakgun/src/gate-2024/stront90spectrum.txt
/gate/source/str90hist/gps/angtype iso
/gate/source/str90hist/gps/mintheta 0. deg
/gate/source/str90hist/gps/maxtheta 180. deg
/gate/source/str90hist/gps/minphi 0. deg
/gate/source/str90hist/gps/maxphi 360. deg

/control/execute visu.mac

#/gate/output/root/enable
#/gate/output/root/setRootHitFlag            1
#/gate/output/root/setRootSinglesFlag        1
#/gate/output/root/setRootNtupleFlag         1
#/gate/output/root/setFileName output/closerStrBC412ROOT

/gate/output/tree/enable
/gate/output/tree/addFileName output/p.csv
/gate/output/tree/hits/enable
/gate/output/tree/addCollection Singles

#/gate/output/ascii(**binary**)/enable
#/gate/output/ascii/setFileName  output/irleDepoutput/strontest.txt
#
## enable ascii(**binary**) output for hits
#/gate/output/ascii(**binary**)/setOutFileHitsFlag   1

/gate/application/setTotalNumberOfPrimaries 10
/gate/application/start
